# Generated by Django 3.2 on 2022-03-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti_index_0',
            field=models.CharField(choices=[('I', 'I'), ('E', 'E')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='mbti_index_1',
            field=models.CharField(choices=[('N', 'N'), ('S', 'S')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='mbti_index_2',
            field=models.CharField(choices=[('F', 'F'), ('T', 'T')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='mbti_index_3',
            field=models.CharField(choices=[('P', 'P'), ('J', 'J')], default='', max_length=1),
        ),
    ]
