# Generated by Django 3.2 on 2022-05-12 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_competitionchoice_competition'),
        ('accounts', '0011_auto_20220512_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitionofthisweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='saved_competition',
            field=models.ManyToManyField(related_name='saved_competition_set', through='accounts.SavedCompetition', to='home.CompetitionOfThisWeek'),
        ),
    ]
