version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    environment:
      - DEBUG=1
      - STAGE=dev
      - DJANGO_SETTINGS_MODULE=config.settings-dev
    depends_on:
      - db
  db:
    image: postgres:12.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5632:5432 
    environment:
      - POSTGRES_USER=trayd_village
      - POSTGRES_PASSWORD=village
      - POSTGRES_DB=trayd_village
volumes:
  postgres_data: