version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile/Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000
    env_file:
      - .env/.env.prod
  nginx-proxy-village:
    container_name: nginx-proxy-village
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-acem:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    env_file:
      - .env/.env.prod.nginx-proxy-acem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy-village
volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
