FROM python:3.9.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /usr/src/app

# install psycopg2 dependencies
RUN apt-get update 
RUN apt-get install -y gcc musl-dev libffi-dev netcat vim

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# install dependencies
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install poetry
COPY ./poetry.lock .
COPY ./pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry install

COPY . .

RUN chmod +x ./entrypoint/entrypoint.dev.sh

ENTRYPOINT ["/usr/src/app/entrypoint/entrypoint.dev.sh"]