# Generated by Django 3.2 on 2022-04-13 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_mbti_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ct001', '일상'), ('ct002', '고민상담'), ('ct003', '연애'), ('ct004', '질문'), ('ct005', '여가'), ('ct006', '취향'), ('ct007', '재테크'), ('ct008', '다이어트'), ('ct009', '취미생활')], max_length=20), size=None),
        ),
    ]
