# Generated by Django 3.2 on 2022-04-14 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ct001', '일상'), ('ct002', '취미'), ('ct003', '연애'), ('ct004', '고민상담'), ('ct005', '쇼핑'), ('ct006', '재테크'), ('ct007', '친구'), ('ct008', '여행'), ('ct009', '다이어트'), ('ct010', '질문')], max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
