# Generated by Django 3.2 on 2022-04-15 03:17

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=common.utils.rename_imagefile_to_uuid),
        ),
    ]
