# Generated by Django 3.2 on 2022-04-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='url',
        ),
    ]
