# Generated by Django 3.2 on 2022-04-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220418_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
