# Generated by Django 3.2 on 2022-04-22 01:46

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20220420_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=common.utils.rename_imagefile_to_uuid_for_comment)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PostReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='postsubcommentlike',
            name='post_subcomment',
        ),
        migrations.RemoveField(
            model_name='postsubcommentlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostSubComment',
        ),
        migrations.DeleteModel(
            name='PostSubCommentLike',
        ),
        migrations.AddField(
            model_name='postreply',
            name='like_user',
            field=models.ManyToManyField(related_name='like_post_reply_set', through='posts.PostReplyLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreply',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment'),
        ),
    ]
