# Generated by Django 3.2 on 2022-04-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20220422_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.postcomment'),
        ),
    ]
