# Generated by Django 3.2 on 2022-05-04 05:10

import common.utils
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=common.utils.rename_imagefile_to_uuid_for_comment)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=common.utils.rename_imagefile_to_uuid_for_comment)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='home.competitioncomment')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('competition_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitionreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competitionreply',
            name='like_user',
            field=models.ManyToManyField(related_name='like_competition_reply_set', through='home.CompetitionReplyLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompetitionOfThisWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closing_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('hits', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like_user', models.ManyToManyField(related_name='like_competition_set', through='home.CompetitionLike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='competitionlike',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitionofthisweek'),
        ),
        migrations.AddField(
            model_name='competitionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompetitionCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('competition_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competitioncomment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitionofthisweek'),
        ),
        migrations.AddField(
            model_name='competitioncomment',
            name='like_user',
            field=models.ManyToManyField(related_name='like_competition_comment_set', through='home.CompetitionCommentLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompetitionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('choice_text', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('selected_users_pk', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competitionofthisweek')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
