# Generated by Django 3.2 on 2022-05-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220504_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionchoice',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='home.competitionofthisweek'),
        ),
    ]
